language: c
os: osx
script: gcc -o booleans booleans.c
skip_cleanup: true
deploy:
  provider: releases
  api_key:
    secure: jIegKHW6VB3OED+RyQEa7KISZETnpGqMREbjExVVJU/QbYFnJ4tTQv1ciIbuh85My7R8hA7YWcr8wD3F8B5jOml4b+Na7BOgfccY7kXa72IIt+ShOTm0AQl9pFpMm05Q2w98ItTBqC93OjlEZBBo0nJoBOOBlULMjzJQbzD5JwFrCiwHcx9iDtY8QkrE4SDBVGDal4s8mh/DQsD0tfTeevgAa2t985P+9IeyAmSiIMPR0OENIC5gLPQdbsj0IKrzj5gZw3gA0UCGyKGU5ObWbqqjqkmPj1zxAYoTyZv021tVywJrH5gsGK8HvwklZPtQjMLmQEDIaHahSP1JjguiQowXjcIC4L1N9k6kR+71Rgkpa0WCnT56NbOgfMXAOzyjc1ZkJv/tRiYerHyB1nRdU8gFYvby2N7/7cG2/1mewH1HCdDu0w427rtvg1wWdIxpDN1c3skqlHJbK0kZ3TMv4GgVKOw//JFGCN5qIeodgS2Ul6Me+j6BxHqlEPUvrlxdrz9u7e0Aui8Ast/AJRJwQ7rIsfM78PybbS+fpUn8yQsSzk4wOKHrajK6wG9wzQG5VDPfG6wmWq68PzVyNsDAiK+pOYc9luTDTEWDtNjjVsTZNq6h+WQOWhnm2ER+m54I2dKpWOReXiw55Q4tezWUHYa9I/N0evI0rOAuJEZNstw=
  file: booleans
  on:
    repo: tmas/travis-ci-testing
    tags: true
    all_branches: true
